import mongoose, { Schema, Document, Model } from "mongoose";

interface PlaylistTrack {
  songId: string;
  songName: string;
  artistName: string;
  albumArt: string;
  source: "audius" | "youtube";
  streamUrl?: string;
  youtubeId?: string;
  duration: number;
}

export interface IPlaylist extends Document {
  userId: mongoose.Types.ObjectId;
  name: string;
  description?: string;
  coverImage?: string;
  tracks: PlaylistTrack[];
  isAutoGenerated: boolean;
  emotion?: string;
  createdAt: Date;
  updatedAt: Date;
}

const PlaylistTrackSchema = new Schema<PlaylistTrack>(
  {
    songId: { type: String, required: true },
    songName: { type: String, required: true },
    artistName: { type: String, required: true },
    albumArt: { type: String, default: "" },
    source: { type: String, enum: ["audius", "youtube"], default: "audius" },
    streamUrl: { type: String, default: "" },
    youtubeId: { type: String, default: "" },
    duration: { type: Number, default: 0 },
  },
  { _id: false }
);

const PlaylistSchema = new Schema<IPlaylist>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    name: { type: String, required: true },
    description: { type: String, default: "" },
    coverImage: { type: String, default: "" },
    tracks: { type: [PlaylistTrackSchema], default: [] },
    isAutoGenerated: { type: Boolean, default: false },
    emotion: { type: String },
  },
  {
    timestamps: true,
  }
);

const Playlist: Model<IPlaylist> =
  mongoose.models.Playlist ||
  mongoose.model<IPlaylist>("Playlist", PlaylistSchema);

export default Playlist;
